### ISSUE TITLE
 Missing output files when running  snakemake

### ISSUE THREAD

**Issue by xiaoxiao349** [Doudna-lab/snakedali#3]
Hi
When I tried to run 
snakemake --snakefile ./nidali/snakedali.smk --configfile ./nidali/config/dali_trial.yaml --profile ./nidali/profile/

I got a bunch of errors saying:
qsub: script file 'smp' cannot be loaded - No such file or directory
Error submitting jobscript (exit code 1):

And the log files say:
Reason: Missing output files: /home/user/xiaox/ecis_DALI/AWS/aws/dali_run_elements/batches/batch_1602/list_batch_1602.txt

Error submitting jobscript (exit code 1):

Any idea or suggestions? Thanks

**Comment by dbellieny** [comment]
Hi @xiaoxiao349 ,

Sorry for not responding earlier. I see that you closed the issue, but I wanted to clarify what the problem was nonetheless: 

The problem you're encountering stems from the fact that your system cannot recognize the default profile for which Snakedali was designed to work. And that is the SGE workload scheduler which is widely used in HPCs. Specifically, the part of the code that is originating the error is where Snakedali requests 10 parallel cores to proceed with its tasks. 
This, of course, can be adjusted to comply with the configuration found in your HPC. 
Let me know how it goes, and feel free to reopen the issue so I can keep supporting you on this.

**Comment by xiaoxiao349** [comment]
Hi Daniel, thanks for your reply and support. I circumvented this issue by running dali.py directly. 

And I've got a question regarding the paper, not the codes. Don't know if it's proper to ask it here. If it's not, please just ignore it and I'll email relevant authors.

The hits after DALI-searches are just cluster representatives of the AlphaFold database. So we should blast the sequences of the hits to get a more comprehensive list, right?

Thanks.
